# Generated by Django 3.2.16 on 2023-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ID', models.IntegerField(verbose_name='ID вопроса')),
                ('question', models.TextField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=200, verbose_name='Ответ  на вопрос')),
                ('data_created', models.DateTimeField(verbose_name='Дата создания вопроса')),
            ],
        ),
    ]
