# Generated by Django 4.2.1 on 2023-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID вопроса')),
                ('question', models.TextField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=200, verbose_name='Ответ  на вопрос')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания вопроса')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
