# Generated by Django 4.2.1 on 2023-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_delete_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата загрузки В БД'),
        ),
    ]
