# Generated by Django 4.2.1 on 2023-06-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_data_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=200, null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Дата создания вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=200, null=True, verbose_name='Текст вопроса'),
        ),
    ]
